apiVersion: v1
kind: Service
metadata:
  name: javatom
  labels:
    app: javatom
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
     
      protocol: TCP
  selector:
    app: javatom
